#!/usr/bin/env bash
#
# rofi with flags for my PC/Laptop.

[[ "$HOSTNAME" == "vio" ]] && \
    font="futuraPT 25"

rofi rofi -modi drun,run,colorscheme:rofi-colorscheme-switch,keys,ssh,combi -show drun \
     -font "${font:-Artwiz Lemon 12}" \
     -separator-style none \
     -scrollbar-width 0 \
     -location 1 \
     -yoffset "${BAR_HEIGHT:-30}" \
     -lines 10 \
     -width 30 \
     -bw 0 \
